*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 07.12.2021 at 18:33:18
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZSHCH_D_CONTACT.................................*
DATA:  BEGIN OF STATUS_ZSHCH_D_CONTACT               .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZSHCH_D_CONTACT               .
CONTROLS: TCTRL_ZSHCH_D_CONTACT
            TYPE TABLEVIEW USING SCREEN '0202'.
*...processing: ZSHCH_V_CONTACT.................................*
TABLES: ZSHCH_V_CONTACT, *ZSHCH_V_CONTACT. "view work areas
CONTROLS: TCTRL_ZSHCH_V_CONTACT
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZSHCH_V_CONTACT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSHCH_V_CONTACT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSHCH_V_CONTACT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_CONTACT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_CONTACT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSHCH_V_CONTACT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_CONTACT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_CONTACT_TOTAL.

*...processing: ZSHCH_V_OWNER...................................*
TABLES: ZSHCH_V_OWNER, *ZSHCH_V_OWNER. "view work areas
CONTROLS: TCTRL_ZSHCH_V_OWNER
TYPE TABLEVIEW USING SCREEN '0201'.
DATA: BEGIN OF STATUS_ZSHCH_V_OWNER. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSHCH_V_OWNER.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSHCH_V_OWNER_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_OWNER.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_OWNER_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSHCH_V_OWNER_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_OWNER.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_OWNER_TOTAL.

*...processing: ZSHCH_V_PTYPE...................................*
TABLES: ZSHCH_V_PTYPE, *ZSHCH_V_PTYPE. "view work areas
CONTROLS: TCTRL_ZSHCH_V_PTYPE
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZSHCH_V_PTYPE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSHCH_V_PTYPE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSHCH_V_PTYPE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_PTYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_PTYPE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSHCH_V_PTYPE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_PTYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_PTYPE_TOTAL.

*...processing: ZSHCH_V_RENTER..................................*
TABLES: ZSHCH_V_RENTER, *ZSHCH_V_RENTER. "view work areas
CONTROLS: TCTRL_ZSHCH_V_RENTER
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZSHCH_V_RENTER. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSHCH_V_RENTER.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSHCH_V_RENTER_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_RENTER.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_RENTER_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSHCH_V_RENTER_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_RENTER.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_RENTER_TOTAL.

*...processing: ZSHCH_V_SP_FIN..................................*
TABLES: ZSHCH_V_SP_FIN, *ZSHCH_V_SP_FIN. "view work areas
CONTROLS: TCTRL_ZSHCH_V_SP_FIN
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZSHCH_V_SP_FIN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSHCH_V_SP_FIN.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSHCH_V_SP_FIN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_SP_FIN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_SP_FIN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSHCH_V_SP_FIN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_SP_FIN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_SP_FIN_TOTAL.

*...processing: ZSHCH_V_STYPE...................................*
TABLES: ZSHCH_V_STYPE, *ZSHCH_V_STYPE. "view work areas
CONTROLS: TCTRL_ZSHCH_V_STYPE
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZSHCH_V_STYPE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZSHCH_V_STYPE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZSHCH_V_STYPE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_STYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_STYPE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZSHCH_V_STYPE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZSHCH_V_STYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZSHCH_V_STYPE_TOTAL.

*.........table declarations:.................................*
TABLES: *ZSHCH_D_CONTACT               .
TABLES: ZSHCH_D_CONTACT                .
TABLES: ZSHCH_D_OWNER                  .
TABLES: ZSHCH_D_OWNER_T                .
TABLES: ZSHCH_D_PTYPE                  .
TABLES: ZSHCH_D_RENTER                 .
TABLES: ZSHCH_D_RENTER_T               .
TABLES: ZSHCH_D_STYPE                  .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
